project:
  type: website

website:
  title: "242"
  favicon: favicon_io/favicon.ico
  search: false
  back-to-top-navigation: false
  open-graph: true
  navbar:
    background: black
    pinned: true
  twitter-card:
    creator: "@laiyenju"
    site: "@242"
format:
  html:
    theme: 
      - cyborg
      - custom.scss
    css: styles.css
    code-copy: hover
    code-overflow: wrap
    code-link: true
    highlight-style: dracula
    anchor-sections: false
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 3
    toc-location: right
    reference-location: margin
    citation-location: margin

execute:
  freeze: auto
