project:
  type: website

website:
  title: "242"
  back-to-top-navigation: false
  open-graph: true
  navbar:
    background: black
    search: true
  twitter-card:
    creator: "@laiyenju"
    site: "@242"
  body-header: | 
    This site is brought to you by [Yen Lai](https://laiyenju.github.io)
format:
  html:
    theme: 
      - cyborg
      - custom.scss
    css: styles.css
    code-copy: hover
    code-link: true
    anchor-sections: false
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 1

execute:
  freeze: auto
