project:
  type: website

website:
  title: "242"
  search: false
  back-to-top-navigation: false
  open-graph: true
  navbar:
    background: black
    pinned: true
  twitter-card:
    creator: "@laiyenju"
    site: "@242"
  margin-header: | 
    This site is brought to you by [Yen Lai](https://read.cv/yenlai)
format:
  html:
    theme: 
      - cyborg
      - custom.scss
    css: styles.css
    code-copy: hover
    code-link: true
    anchor-sections: false
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 1
    reference-location: margin
    citation-location: margin

execute:
  freeze: auto
